@host = http://localhost:8000

### login
# @name login
POST {{host}}/login
Content-Type: application/json

{
  "user": 
    {
      "email": "carloshdelreal@gmail.com",
      "password": "123456"
    }
}

### current user
GET {{host}}/current_user
Content-Type: application/json
Authorization: {{login.response.headers.Authorization}}

### get film_people
GET {{host}}/film_people
Authorization: {{login.response.headers.Authorization}}
### create film_people
POST {{host}}/film_people
Authorization: {{login.response.headers.Authorization}}
Content-Type: application/json

{
  "film_person": {
    "film_id": 1,
    "person_id": 1
  }
}

### update
PUT {{host}}/film_people/163
Authorization: {{login.response.headers.Authorization}}
Content-Type: application/json

{
  "film_person": {
    "film_id": 1,
    "person_id": 2
  }
}



### delete film_people
DELETE {{host}}/film_people/163
Authorization: {{login.response.headers.Authorization}}
Content-Type: application/json

### show film_people
GET {{host}}/film_people/33
Authorization: {{login.response.headers.Authorization}}
Content-Type: application/json