@host = http://localhost:8000

### sign up
POST {{host}}/signup
Content-Type: application/json

{
  "user": 
    {
      "email": "carloshdelreal@gmail.com",
      "password": "123456"
    }
}

### login
# @name login
POST {{host}}/login
Content-Type: application/json

{
  "user": 
    {
      "email": "carloshdelreal@gmail.com",
      "password": "123456"
    }
}

### current user
GET {{host}}/current_user
Content-Type: application/json
Authorization: {{login.response.headers.Authorization}}


### login wrong credentials
POST {{host}}/login
Content-Type: application/json

{
  "user": 
    {
      "email": "carloshdelreal@gmail.com",
      "password": "wrongpass"
    }
}

### sign_out
DELETE {{host}}/logout
Authorization: {{login.response.headers.Authorization}}
Content-Type: application/json


### forgot password
POST {{host}}/password/forgot
Content-Type: application/json

{
  "email": "carloshdelreal@gmail.com"
}


### reset password
POST {{host}}/password/reset
Content-Type: application/json

{
  "email": "carloshdelreal@gmail.com",
  "password": "newpass",
  "token": "3f7a446b4862389ae73a"
}
